version: '3'
services:
  nodejs:
    image: gabriel/app-node:latest
    build: .
    command: npm start
    ports:
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  web:
    image: nginx
    volumes:
    - ./nginx/app.conf:/etc/nginx/nginx.conf
    depends_on:
    - minha_app
    ports:
    - 80:80